### ISSUE TITLE
Encoding

### ISSUE THREAD

**Issue by JordanMajd** [shbhrsaha/spamchat#1]
Excuse me, I'm not very familiar with python so I might just be an idiot.

Initially I got an error the error

```
         unicode objects must be encoded before hashing
```

for both of the 

```
hashlib.sha256().hexdigest 
```

calls in request_token, I got past this by doing:

```
         todigestfirst = pattern + auth_token
         todigestfirst = todigestfirst.encode('utf-8')
         first = hashlib.sha256(todigestfirst).hexdigest()
         todigestsecond = str(timestamp) + secret
         todigestsecond = todigestsecond.encode('utf-8')
         second = hashlib.sha256(todigestsecond).hexdigest()
```

However when I make the 

```
TOKEN = requests.post(HOST+"/bq/login" , params).json()["auth_token"]
```

I now get the error:

```
         ValueError: No JSON object could be decoded
```

Meaning that a json object isn't being returned. This could be due to how I encoded the request token.

Do you have any advice? Thank you.

**Comment by shbhrsaha** [comment]
Sure, can you run after inserting

```
print requests.post(HOST+"/bq/login" , params)
```

after line 58 and return the result?

Also, try encoding with ascii instead of utf-8.

**Comment by JordanMajd** [comment]
Thanks for the quick response!

I figured it out however, python 3.3 handles encoding differently so I downgraded to 2.6 and downgraded requests to 1.2.3 for another that came up and now it runs perfectly.

Well almost perfect, it sends out the snap but I can't open them. It just says Press and hold to view, tries to load it, and then returns to press and hold to view when I click. Are you able to open the snaps you send? Tried JPG and PNG. I added a print so I could see that it is reading the correct files and 

```
for file_name in FILES:
    with open(file_name) as f:
        data = f.read()
    print (file_name)
```

my result is:

```
images/rawrjpg.jpg
images/rawrpng.png
```

I'm wondering if I'm encoding the image wrong with

```
with open(file_name) as f:
```

What version of python are you running?

**Comment by shbhrsaha** [comment]
Great to hear. I just added a requirements.txt and updated the README to include my Python version and library version. Lemme know if that helps! Also just make sure your image is about iPhone size-- I've had problems with some images being too large. JPEGs should work.

**Comment by Nsimitzi** [comment]
I am also not too familiar with Python, so forgive my stupidity.
Anyways, I am receiving this error when I attempt to run spamchat.py.

```
Traceback (most recent call last):
  File "/Users/Brevens/Desktop/spamchat-master/spamchat.py", line 59, in <module>
    TOKEN = requests.post(HOST+"/bq/login" , params).json()["auth_token"]
  File "/Library/Python/2.7/site-packages/requests-2.2.1-py2.7.egg/requests/models.py", line 741, in json
    return json.loads(self.text, **kwargs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 365, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 383, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
```

I added some lines that lordbunson suggested to add.

```
    # get a connection
    params = {"username" : USERNAME, "password" : PASSWORD, "timestamp": TIMESTAMP\
            , "req_token" : request_token(STATIC_TOKEN, TIMESTAMP)}
    TOKEN = requests.post(HOST+"/bq/login" , params).json()["auth_token"]
    todigestfirst = pattern + auth_token
    todigestfirst = todigestfirst.encode('ascii')
    first = hashlib.sha256(todigestfirst).hexdigest()
    todigestsecond = str(timestamp) + secret
    todigestsecond = todigestsecond.encode('ascii')
    second = hashlib.sha256(todigestsecond).hexdigest()

    for file_name in FILES:
        with open(file_name) as f:
            data = f.read()
        print (file_name)
```

let me know if you need any other info. I am running 3.4 on mac osx Mavericks
